# Generated by Django 4.2.5 on 2023-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(help_text='Id of the partner', unique=True)),
                ('name', models.CharField(help_text='Name', max_length=120)),
                ('email', models.EmailField(help_text='Email', max_length=256)),
                ('country_code', models.CharField(help_text='The ISO country code in two chars.', max_length=3)),
                ('employee', models.BooleanField(help_text='Check this box if this contact is an Employee.')),
                ('is_company', models.BooleanField(help_text='Check if the contact is a company, otherwise it is a person')),
            ],
        ),
    ]
